---
# tasks file for HackMD

- name: Update default SELinux contexts
  sefcontext:
    target: '{{ item }}(/.*)?'
    setype: "svirt_sandbox_file_t"
    state: present
  with_items:
    - "{{ hackmd_database_location }}"
  become: true


- name: Create directory
  file:
    path: "{{ item }}"
    state: directory
    setype: "svirt_sandbox_file_t"
  with_items:
    - "{{ hackmd_install_location }}"
    - "{{ hackmd_database_location }}"
  become: true


- name: Deploy docker-compose.yml
  template:
    src: docker-compose.yml
    dest: "{{ hackmd_install_location }}/docker-compose.yml"
  register: docker_compose_yml
  tags:
    - docker
    - hackmd
  become: true


- name: Compose hackmd
  docker_service:
    state: present
    project_src:  "{{ hackmd_install_location }}"
    pull: yes
  register: compose_hackmd
  become: true
