---
# defaults file for hackmd

hackmd_install_location: /var/srv/hackmd
hackmd_database_location: "{{ hackmd_install_location }}/database"

hackmd_domain: pad.example.com
hackmd_options:
  ALLOW_FREE_URL: false
  HMD_DOMAIN: "{{ hackmd_domain }}"
  EMAIL: false
  PROTOCOL_USESSL: true
  URL_ADDPORT: false
  USECDN: true

  hackmd_version: 1.0.1-ce
hackmd_postgres_version: 9.6

hackmd_image_version: "{{ hackmd_version }}"
hackmd_postgres_image_version: "{{ hackmd_postgres_version }}-alpine"

